version: '3.8'

services:
  pdb-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount local code for development; Uvicorn's reload should pick up changes.
      # For production, you might remove this or use a more optimized image build.
      - ./mcp_pdb:/app/mcp_pdb 
    # environment:
      # - LOG_LEVEL=DEBUG # Example: override log level from config.py
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8000/"] # Basic health check
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
